import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:ableone_app/config/app_config.dart';
import 'package:ableone_app/features/ai/domain/entities/ai_context_entity.dart';

class GeminiApiService {
  final http.Client _client;

  GeminiApiService({http.Client? client}) : _client = client ?? http.Client();

  Future<String> sendPrompt(String prompt, AIContextEntity context) async {
    final apiKey = AppConfig.geminiApiKey;
    if (apiKey.isEmpty) {
      throw Exception('Gemini API key is not configured in .env file.');
    }

    final url = Uri.parse(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$apiKey',
    );

    final supportDesc = context.accessibilityNeeds.isEmpty ? 'None' : context.accessibilityNeeds.join(', ');
    final courseText = context.currentCourse != null ? context.currentCourse!.title : 'None';
    final lessonText = context.currentLesson != null ? context.currentLesson!.title : 'None';

    final systemInstruction = 'You are AbleOne AI Tutor.\n\n'
        'Student level: ${context.userLevel}.\n'
        'Accessibility needs: $supportDesc.\n'
        'Learning preference: ${context.learningPreference}.\n'
        'Preferred language: ${context.language}.\n\n'
        'Current course: $courseText.\n'
        'Current lesson: $lessonText.\n\n'
        'Explain using simple examples. Tailor your formatting, structure, and complexity to the student\'s profile above. '
        'If a lesson is actively set, prioritize explaining or referencing that topic.';

    final requestBody = {
      'contents': [
        {
          'role': 'user',
          'parts': [
            {'text': prompt}
          ]
        }
      ],
      'systemInstruction': {
        'parts': [
          {'text': systemInstruction}
        ]
      },
      'generationConfig': {
        'temperature': 0.7,
        'maxOutputTokens': 1000,
      }
    };

    try {
      final response = await _client.post(
        url,
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode(requestBody),
      );

      if (response.statusCode != 200) {
        String detail = '';
        try {
          final errBody = jsonDecode(response.body) as Map<String, dynamic>;
          final err = errBody['error'] as Map<String, dynamic>?;
          detail = err?['message'] as String? ?? '';
        } catch (_) {}
        throw Exception(
          'API failure: Gemini returned error code ${response.statusCode}${detail.isNotEmpty ? ": $detail" : ""}',
        );
      }

      final responseJson = jsonDecode(response.body) as Map<String, dynamic>;
      final candidates = responseJson['candidates'] as List<dynamic>?;
      if (candidates == null || candidates.isEmpty) {
        throw Exception('No responses generated by the Gemini model.');
      }
      final candidate = candidates[0] as Map<String, dynamic>;
      final content = candidate['content'] as Map<String, dynamic>?;
      final parts = content?['parts'] as List<dynamic>?;
      if (parts == null || parts.isEmpty) {
        throw Exception('Response parts are empty.');
      }
      final text = parts[0]['text'] as String?;
      if (text == null) {
        throw Exception('Response text is null.');
      }

      return text.trim();
    } catch (e) {
      final errStr = e.toString().toLowerCase();
      if (errStr.contains('socketexception') || errStr.contains('failed host lookup') || errStr.contains('handshake')) {
        throw Exception('No internet connection. Please check your network and try again.');
      }
      if (e is Exception) {
        rethrow;
      }
      throw Exception('Failed to connect to Gemini API: ${e.toString()}');
    }
  }
}
