import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:ableone_app/config/app_config.dart';
import 'package:ableone_app/features/ai/domain/entities/ai_user_context.dart';
import 'package:ableone_app/features/ai/domain/services/ai_service.dart';

/// Gemini implementation of [AIService], fetching real-time model responses.
class GeminiDatasource implements AIService {
  final http.Client _client;

  /// Creates a [GeminiDatasource] instance.
  GeminiDatasource({http.Client? client}) : _client = client ?? http.Client();

  /// Requests response content from Gemini 1.5 Flash using the compiled API key,
  /// passing the active user profile [context] within system instructions.
  @override
  Future<String> generateResponse(String prompt, AIUserContext context) async {
    final apiKey = AppConfig.geminiApiKey;
    if (apiKey.isEmpty) {
      throw Exception(
        'Gemini API key is not configured in the application environment. '
        'Please build the application with --dart-define=GEMINI_API_KEY=your_key.',
      );
    }

    final url = Uri.parse(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$apiKey',
    );

    // Build personalization system instructions
    final supportDesc = context.supportNeeds.isEmpty ? 'None' : context.supportNeeds.join(', ');
    final systemInstruction = 'You are a helpful and supportive AI Tutor in the AbleOne inclusive education system. '
        'Your goal is to explain, summarize, translate, or simplify concepts based on the student\'s profile.\n'
        'Student profile rules to strictly respect:\n'
        '- Learning/Explanation Level: ${context.learningLevel}\n'
        '- Preferred Style/Explanations Preference: ${context.learningPreference}\n'
        '- Active Support Needs: $supportDesc\n'
        '- Interface & Explanation Language: ${context.preferredLanguage}\n'
        'Tailor your tone, structure, complexity, formatting, and choice of words to this profile. '
        'If the student has support needs like "Visual Support", use rich structural spacing and illustrative emojis. '
        'Respond in the preferred language. Keep explanations accessible and structured.';

    final requestBody = {
      'contents': [
        {
          'role': 'user',
          'parts': [
            {'text': prompt}
          ]
        }
      ],
      'systemInstruction': {
        'parts': [
          {'text': systemInstruction}
        ]
      },
      'generationConfig': {
        'temperature': 0.7,
        'maxOutputTokens': 1000,
      }
    };

    try {
      final response = await _client.post(
        url,
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode(requestBody),
      );

      if (response.statusCode != 200) {
        String detail = '';
        try {
          final errBody = jsonDecode(response.body) as Map<String, dynamic>;
          final err = errBody['error'] as Map<String, dynamic>?;
          detail = err?['message'] as String? ?? '';
        } catch (_) {}
        throw Exception(
          'Gemini API returned error code ${response.statusCode}${detail.isNotEmpty ? ": $detail" : ""}',
        );
      }

      final responseJson = jsonDecode(response.body) as Map<String, dynamic>;
      final candidates = responseJson['candidates'] as List<dynamic>?;
      if (candidates == null || candidates.isEmpty) {
        throw Exception('No responses generated by the Gemini model.');
      }
      final candidate = candidates[0] as Map<String, dynamic>;
      final content = candidate['content'] as Map<String, dynamic>?;
      final parts = content?['parts'] as List<dynamic>?;
      if (parts == null || parts.isEmpty) {
        throw Exception('Response parts are empty.');
      }
      final text = parts[0]['text'] as String?;
      if (text == null) {
        throw Exception('Response text is null.');
      }

      return text.trim();
    } catch (e) {
      if (e is Exception) {
        rethrow;
      }
      throw Exception('Failed to connect to Gemini API: ${e.toString()}');
    }
  }
}
