import 'package:ableone_app/features/ai/domain/entities/ai_user_context.dart';
import 'package:ableone_app/features/ai/domain/services/ai_service.dart';

/// Gemini implementation of [AIService], providing simulated response generation.
class GeminiDatasource implements AIService {
  /// Simulates a network call delay and returns mock Gemini responses customized
  /// by the active [context] to preserve personalization settings.
  @override
  Future<String> generateResponse(String prompt, AIUserContext context) async {
    // Simulate API call latency
    await Future.delayed(const Duration(milliseconds: 1500));

    final normalized = prompt.toLowerCase().trim();
    String responseText = '';

    if (normalized.contains('photosynthesis')) {
      responseText = 'Hello! Gemini has simulated this response on photosynthesis:\n\n'
          'Photosynthesis is how green plants use sunlight to synthesize nutrients from carbon dioxide and water. '
          'Since you prefer "${context.learningPreference}", let\'s simplify it:\n\n'
          '☀️ Sunlight + 💧 Water + 💨 Air = 🌲 Plant Energy + 🌬️ Fresh Oxygen!';
    } else if (normalized.contains('explain')) {
      responseText = 'As your Gemini AI Tutor, I can break down any educational topic for you. '
          'Please type a topic name, and I will prepare a detailed review tailored to your '
          '${context.learningLevel} level and ${context.learningPreference} style!';
    } else if (normalized.contains('summarize') || normalized.contains('summary')) {
      responseText = 'Here is a quick summary generated by Gemini:\n\n'
          '• Sight words are commonly used words that young readers are encouraged to recognize as a whole by sight.\n'
          '• Repetition and interactive word games help lock these in.\n'
          '• Daily target: Practice for at least 5-10 minutes.';
    } else if (normalized.contains('quiz')) {
      responseText = 'Gemini Quiz Builder:\n\n'
          'Choose the word that completes the sentence:\n'
          '"The cat sat on ____ mat."\n\n'
          '1️⃣ standard\n2️⃣ the\n3️⃣ run';
    } else if (normalized.contains('translate')) {
      responseText = 'Here is your translation:\n\n'
          '• "Hello, learn with me" -> *"Hola, aprende conmigo"* (Spanish)\n'
          '• Target Language: Spanish\n\n'
          'Feel free to give me more phrases to translate!';
    } else if (normalized.contains('simplify')) {
      responseText = 'Gemini Simplification Tool:\n\n'
          'Original: "Cognitive comprehension requires active retention."\n'
          'Simplified: "Remembering what you read is the key to learning!"';
    } else {
      responseText = 'Hello! I am your new Gemini AI Tutor. '
          'I\'ve received your prompt: "$prompt". How can I support your learning goals today?';
    }

    // Append context-based signature
    final supportDesc = context.supportNeeds.isEmpty ? 'No custom support needs' : context.supportNeeds.join(', ');
    final contextInfo = '\n\n*(Gemini Mode • Level: ${context.learningLevel} • Preference: ${context.learningPreference} • Needs: $supportDesc)*';

    return '$responseText$contextInfo';
  }
}
